BEGIN;

CREATE TABLE IF NOT EXISTS competitor(
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	country VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS theme(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS event(
	id SERIAL PRIMARY KEY,
	name VARCHAR(150) NOT NULL UNIQUE,
	started_at TIMESTAMP NOT NULL,
	finished_at TIMESTAMP NOT NULL,
	theme_id SERIAL NOT NULL,
	CONSTRAINT fk_theme_id FOREIGN KEY(theme_id) REFERENCES theme(id)
);

CREATE TABLE IF NOT EXISTS competition(
	event_id SERIAL NOT NULL REFERENCES event(id) ON DELETE CASCADE,
	competitor_id SERIAL NOT NULL REFERENCES competitor(id) ON DELETE CASCADE,
	score NUMERIC(4,2) NOT NULL,
	CHECK( score > 0 AND score <= 100)
);

COMMIT;